spring:
  application:
    name: emotion_gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://users-service
            predicates:
              - Path=/v1/emotion/user/**
            filters:
              - AddRequestHeader=Service-Request, user-service
              - RewritePath=/v1/emotion/user/?(?<segment>.*),/api/v1/user/$\{segment}

          - id: workouts-service
            uri: http://workouts-service
            predicates:
              - Path=/v1/emotion/workouts/**
            filters:
              - AddRequestHeader=Service-Request, workouts-service
              - RewritePath=/v1/emotion/workouts/?(?<segment>.*),/api/v1/workouts/$\{segment}


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

